backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images" # The src attribute for uploaded media will begin with /images/uploads
